export const categoryData = {
  message: "부스 목록 조회 성공",
  data: [
    {
      id: 1,
      user: 1,
      day: ["수요일", "목요일", "금요일"],
      college: "포스코관",
      name: "멋쟁이 사자처럼",
      number: "포08",
      image: "",
      is_liked: false,
      created_at: "2022-08-12 16:21",
      updated_at: "2022-08-12 22:34",
    },
    {
      id: 2,
      user: 2,
      day: ["목요일", "금요일"],
      college: "경영관",
      name: "멋쟁이 호랑이처럼",
      number: "경영12",
      image: "",
      is_liked: false,
      created_at: "2022-08-12 16:21",
      updated_at: "2022-08-12 22:35",
    },
    {
      id: 3,
      user: 4,
      day: ["수요일", "목요일", "금요일"],
      college: "학관",
      name: "멋쟁이 토마토처럼",
      number: "학02",
      image: "",
      is_liked: true,
      created_at: "2022-08-12 16:21",
      updated_at: "2022-08-12 22:35",
    },
  ],
};
